/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.universidad.universdiad;
import com.universidad.universidad.dao.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;
/**
 *
 * @author Familia Ramirez
 */
public class RectoresForm extends javax.swing.JDialog {

    private Rectores currentRectores;
    private boolean _reloadParent = false;
    private String _mode;
    
    public boolean getReloadParent(){
        return _reloadParent;
    }
    
    public RectoresForm(String Mode, double id) {
        initComponents();
        setModal(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        _mode = Mode;
        if (!Mode.equals("INS")){
   
            System.out.println(id);
            currentRectores = UniversidadMode.getRectoresById(id);
            jTSiglas.setText(currentRectores.getSIGLAS());
            jTNombreCampus.setText(currentRectores.getNOMBREUNIVERSIDAD());
            jTNombreRector.setText(currentRectores.getNOMBRECAMPUS());   
        } else {
            currentRectores = new Rectores();
        }
        switch(Mode){
            case "INS":
                jLTitle.setText("Agregando nuevo Rector");
                jBAgregar.setText("Agregar");
                break;
            case "UPD":
                jLTitle.setText(String.format("Actualizando Rectores %.0f %s", currentRectores.getID(), currentRectores.getNOMBRECAMPUS()));
                jBAgregar.setText("Editar");
                break;
            case "DEL":
                jLTitle.setText(String.format("Eliminar Rectores %.0f %s", currentRectores.getID(), currentRectores.getNOMBRECAMPUS()));
                deshabilitarCampos();
                jBAgregar.setText("Eliminar");
                break;
            case "DSP":
                jBAgregar.setVisible(false);
                jBCancelar.setText("Salir");
                deshabilitarCampos();
                jLTitle.setText(String.format("Rectores %.0f %s", currentRectores.getID(), currentRectores.getNOMBRECAMPUS()));
                break;
        }
        
    }
    
    /**
     * Creates new form RectoresForm
     */
    public RectoresForm() {
        initComponents();
    }

    private void deshabilitarCampos(){
        jTSiglas.setEditable(false);
        jTNombreCampus.setEditable(false);
        jTNombreRector.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTNombreCampus = new javax.swing.JTextField();
        jTSiglas = new javax.swing.JTextField();
        jTNombreRector = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(450, 370));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAgregarMouseClicked(evt);
            }
        });

        jLTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTitle.setText("Ingresando Datos");

        jLabel2.setText("Siglas del Campus Universitario");

        jLabel3.setText("Nombre del Campus universitario");

        jLabel4.setText("Nombre del Rector");

        jBAgregar.setText("Agregar");
        jBAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAgregarMouseClicked1(evt);
            }
        });
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLTitle)
                                    .addComponent(jTNombreRector, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(jTSiglas)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTNombreCampus, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jTNombreCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNombreRector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar)
                    .addComponent(jBCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMouseClicked
        // TODO add your handling code here:
        
      /*  //Extrer la informacion
        currentRectores.setSIGLAS(jTSiglas.getText());
        currentRectores.setNOMBREUNIVERSIDAD(jTNombreCampus.getText());
        currentRectores.setNOMBRECAMPUS(jTNombreRector.getText());
        
          boolean hayError = false;
        boolean errorNombres = Validaciones.esCadenaVacia(currentRectores.getNOMBRECAMPUS());
        if(errorNombres){
            jTNombreCampus.setBackground(Color.red);
        }else{
            jTNombreRector.setBackground(Color.white);
        }
        System.out.println(errorNombres);
        
        hayError = errorNombres && true;
        if(!hayError){
           switch(_mode){
               case "INS":
                   _reloadParent = UniversidadMode.agregarRectores(currentRectores);
                   break;
               case "UPD":
                   _reloadParent = UniversidadMode.editarRectores(currentRectores);
                   break;
               case "DEL":
                   _reloadParent = UniversidadMode.eliminarRectores(currentRectores);
                   break;
           } 
           
           dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        else{
            // JOptionPane.showConfirmDialog(rootPane, jCEstado)
        }*/
    }//GEN-LAST:event_jBAgregarMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RectoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RectoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RectoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RectoresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RectoresForm().setVisible(true);
            }
        });
    }
    
    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBAgregarMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMouseClicked1
        // TODO add your handling code here:
        currentRectores.setSIGLAS(jTSiglas.getText());
        currentRectores.setNOMBREUNIVERSIDAD(jTNombreCampus.getText());
        currentRectores.setNOMBRECAMPUS(jTNombreRector.getText());
        
          boolean hayError = false;
        boolean errorNombres = Validaciones.esCadenaVacia(currentRectores.getNOMBRECAMPUS());
        if(errorNombres){
            jTNombreCampus.setBackground(Color.red);
        }else{
            jTNombreCampus.setBackground(Color.white);
        }
        System.out.println(errorNombres);
        
        hayError = errorNombres && true;
        if(!hayError){
           switch(_mode){
               case "INS":
                   _reloadParent = UniversidadMode.agregarRectores(currentRectores);
                   break;
               case "UPD":
                   _reloadParent = UniversidadMode.editarRectores(currentRectores);
                   break;
               case "DEL":
                   _reloadParent = UniversidadMode.eliminarRectores(currentRectores);
                   break;
           } 
           
           dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        else{
            //JOptionPane.showConfirmDialog(rootPane, jCEstado);
        }
    }//GEN-LAST:event_jBAgregarMouseClicked1

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
        // TODO add your handling code here:
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jBCancelarMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTNombreCampus;
    private javax.swing.JTextField jTNombreRector;
    private javax.swing.JTextField jTSiglas;
    // End of variables declaration//GEN-END:variables
}
